### ISSUE TITLE
__init__() got an unexpected keyword argument 'log_level'

### ISSUE THREAD

**Issue by nileszzy** [maximedrn/hcaptcha-solver-python-selenium#12]
Hello there, I just tried to use this, but got the following error messages:

```
Traceback (most recent call last):

File "D:/PycharmProjects/pythonProject/hcaptcha-solver/main.py", line 43, in <module>
  browser=1, headless=False, comments=True, download=False)
File "D:\PycharmProjects\pythonProject\hcaptcha-solver\app\hcaptcha.py", line 59, in __init__
  self.driver = self.geckodriver()
File "D:\PycharmProjects\pythonProject\hcaptcha-solver\app\hcaptcha.py", line 97, in geckodriver
  log_level=0).install()), options=options)

TypeError: __init__() got an unexpected keyword argument 'log_level'`
```

**Comment by syzen77777777777** [comment]
why don't you try comparing images instead of using a ? @maximedrn

**Comment by maximedrn** [comment]
> why don't you try comparing images instead of using a ? @maximedrn

Instead of using a userscript? This userscript works on any computer because it uses the Wolfram API instead of the power of your computer.
